### ISSUE TITLE
CVE-2020-13946 for native-protocol

### ISSUE THREAD

**Issue by patpatpat123** [datastax/native-protocol#43]
Hello Native Protocol, hello Datastax,

I would like to write down the findings here, for an issue.

The setup is a Java SpringBoot 2.6.7 + Spring Cloud Jubilee 2021.0.2 (latest as of this writing) writing data to Cassandra.

The web application is run against some static analysis tools, such as Black Duck, SonaQube, OWASP Dependency etc...

All of them flag the same findings:

CVE-2020-13946 for native-protocol-1.5.0.jar.

This has further been confirm when running a tree:

```
[DEBUG]    org.springframework.boot:spring-boot-starter-data-cassandra-reactive:jar:2.6.6:compile
[DEBUG]       org.springframework:spring-tx:jar:5.3.18:compile (version managed from 5.3.18)
[DEBUG]       org.springframework.data:spring-data-cassandra:jar:3.3.3:compile (version managed from 3.3.3)
[DEBUG]          org.springframework:spring-context:jar:5.3.18:compile (version managed from 5.3.17)
[DEBUG]          org.springframework:spring-expression:jar:5.3.18:compile (version managed from 5.3.17)
[DEBUG]          org.springframework.data:spring-data-commons:jar:2.6.3:compile (version managed from 2.6.3)
[DEBUG]          com.datastax.oss:java-driver-core:jar:4.13.0:compile (version managed from 4.13.0) (exclusions managed from [])
[DEBUG]             com.datastax.oss:native-protocol:jar:1.5.0:compile (version managed from 1.5.0)
```

I wanted to start this issue on Java-driver-core, but Issues are disabled there.

With that said, the impact seems to be real. May I ask if it is possible to help fix this CVE?

Maybe by fixing the vulnerability on this repo, and then, bump java-driver-sore to use the newly build with the fix?

Thank you for your time making Datastax products more secure and less vulnerable.

**Comment by ErickRamirezAU** [comment]
I'm happy to be corrected but as I understand it, the vulnerability only exists if BOTH of these conditions are true:

1. You are running an old version of Cassandra.
2. The JMX port is exposed to public access.

The vulnerability doesn't apply to the native protocol. Do you have any other information that says otherwise?

If you're concerned about being vulnerable, we recommend that you upgrade to a supported version of Cassandra. Cheers!

**Comment by patpatpat123** [comment]
Hello @ErickRamirezAU 

Thank you for your answer and your time looking at this.
You are correct, the CVE applies only when certain preconditions are met.

In our case, we do meet the preconditions for the CVE.

I also totally understand and agree with you recommendation which I would like to rephrase as:
"There is a CVE in Datastax's jar when couple of preconditions are met. If one meets the preconditions, this one should upgrade to a newer version of Cassandra"

While this approach make sense, it is neither scalable neither optimum. May I suggest another way to tackle this, such as:
"There is a CVE in Datastax's jar when couple of preconditions are met. Many users around the world are using Cassandra, as it is a popular database. Some of those many users might meet the all preconditions for the vulnerability. There is no way to contact each and everyone who does meet the precondition to force them to update their version. And even is this was possible, a much simpler and nicer fix would be to apply a fix to the vulnerability at it's source, by fixing/improving the code to mitigate the vulnerability where it is happening"

I hope this is not too much of a trouble, and thank you again for your response

**Comment by ErickRamirezAU** [comment]
Let me reiterate -- the vulnerability has nothing to do with the native protocol. The vulnerability exists in JMX which is used for metrics/remote management and is completely separate from the native protocol.

The native protocol is used by apps/clients to connect to the cluster to perform DML/DDL operations. Cheers!

**Comment by patpatpat123** [comment]
Thank you again Eric for following up on this:

Our client is a basic SpringBoot app with recent version 2.6.7 (as of this writing) performing various operations against our Cassandra Cluster.

We can clearly see in the dependency tree: 

```
[DEBUG]    org.springframework.boot:spring-boot-starter-data-cassandra-reactive:jar:2.6.6:compile
[DEBUG]       org.springframework:spring-tx:jar:5.3.18:compile (version managed from 5.3.18)
[DEBUG]       org.springframework.data:spring-data-cassandra:jar:3.3.3:compile (version managed from 3.3.3)
[DEBUG]          org.springframework:spring-context:jar:5.3.18:compile (version managed from 5.3.17)
[DEBUG]          org.springframework:spring-expression:jar:5.3.18:compile (version managed from 5.3.17)
[DEBUG]          org.springframework.data:spring-data-commons:jar:2.6.3:compile (version managed from 2.6.3)
[DEBUG]          com.datastax.oss:java-driver-core:jar:4.13.0:compile (version managed from 4.13.0) (exclusions managed from [])
[DEBUG]             com.datastax.oss:native-protocol:jar:1.5.0:compile (version managed from 1.5.0)
```

org.springframework.boot:spring-boot-starter-data-cassandra-reactive:jar:2.6.6: -> com.datastax.oss:java-driver-core:jar:4.13.0 -> com.datastax.oss:native-protocol:jar:1.5.0

Our app indeed connect to the cluster to perform DML/DDL operations and much more.

Would it be possible to highlight this within one of Datastax internal report please?

Thank you

**Comment by ErickRamirezAU** [comment]
I think there's a big misunderstanding here. It would be easier if we can have a quick conversation if you're willing to do so. You can contact me through here -- https://calendly.com/erickramirezau/catchup. Cheers! 🍻

**Comment by patpatpat123** [comment]
Hello @ErickRamirezAU,

I created a small zip just to highlight the issue.
The zip file can be extracted, and a run with this: "mvn clean install dependency:tree -X” should yield the output:

[WARNING] 
One or more dependencies were identified with known vulnerabilities in demo:
```native-protocol-1.5.0.jar (pkg:maven/com.datastax.oss/native-protocol@1.5.0, cpe:2.3:a:apache:cassandra:1.5.0:*:*:*:*:*:*:*) : CVE-2020-13946```

Before continuing, I was wondering if you get the same thing on your end.

[demo.zip](https://github.com/datastax/native-protocol/files/8705608/demo.zip)

**Comment by absurdfarce** [comment]
Greetings @patpatpat123 !

I did try running the demo you provided and I believe the results can shed some light on what's going on here.  The result does indicate a "dependency with a known vulnerability" with the text cited in your last response.  However that result also mentions that we should "See the dependency-check report for more details.".  That report is indeed pretty useful here.

The report (by default it's at target/dependency-check-report.html) contains some useful information.  It includes a section labelled "Evidence" which appears to show a collection of relevant strings extracted from various bits of the project (Maven POM files, Java package names, various manifests, etc.).  It also includes a section called "Identifiers" which indicates the OWASP plugin's guess as to the package containing the artifact in question as well as the [NVD CPE](https://nvd.nist.gov/products/cpe) (basically a name for the software package used by the NIST NVD) of the affected library.  My report clearly indicates the following:

```
pkg:maven/com.datastax.oss/native-protocol@1.5.0  (Confidence:High)
cpe:2.3:a:apache:cassandra:1.5.0:*:*:*:*:*:*:*  (Confidence:Low)
```

It's fairly obvious from these results that the OWASP Maven plugin has (correctly) determined that the library in question comes from the native-protocol package.  It also seems very much like the plugin has determined (incorrectly) that the library belongs to the Cassandra CPE.  And because CVE-2020-13946 applies to this CPE [1]: 

```
cpe:2.3:a:apache:cassandra:1.5.0:*:*:*:*:*:*:*
```

the artifact is (incorrectly) flagged as being susceptible to the exploit.

It's also worth noting that the OWASP plugin itself marks the identification of this artifact as belonging to the Apache Cassandra CPE as having "low" confidence so some suspicion is quite warranted.

The conclusion of an incorrect identification is further supported by the evidence already presented by @ErickRamirezAU.  It's also supported by the fact that the description of the CVE at NIST lists the "Known Affected Software Configurations" and that list only includes Apache Cassandra and doesn't include native-protocol.  Finally, it's supported by the fact that earlier today I spoke with the Cassandra committer who fixed the issue and he confirmed that the exploit was entirely on the Apache Cassandra server and not related to native-protocol.

Hopefully this analysis is somewhat helpful!

[1] This can be confirmed by looking at the affected CPEs on the [relevant CVE page at NIST](https://nvd.nist.gov/vuln/detail/CVE-2020-13946)

**Comment by patpatpat123** [comment]
Hello @absurdfarce,

This is a very clear explanation which I am very thankful for.
I appreciate your write up, as well as @ErickRamirezAU 's opinion.
This issue is good to close, I will follow up separately with OWASP regarding the false positive, hoping they can enhance this particular scan result.
In the meantime, I am also looking forward to a trying a newer version of Spring Boot, (follow up with Spring Team) where they will use a more up to date version of Java Driver Core, which in turn use a newer version of this native protocol, with the knowledge of this false positive.

Once again, thank you both

**Comment by absurdfarce** [comment]
Sounds good @patpatpat123!

My recommendation would be to focus on a fix for the underlying bug in the OWASP plugin.  I say that because the current version of the 4.x Java driver uses native-protocol 1.5.1, obviously only a patch release different from 1.5.0.  More to the point I strongly suspect most of the metadata collected and evaluated by the OWASP plugin will be identical or at least very similar, so as long as the bug causing this data to be evaluated as belonging to the Cassandra CPE is still in place you'll see very similar behaviour from that version as well.  If that's the case then there isn't much the Spring folks can do to make this better.

There's probably no harm in filing a ticket with them; the analysis above could be wrong of incomplete.  I merely mean to suggest that any fix to the OWASP plugin will likely be the robust fix for the underlying problem.

Thanks again, and good luck @patpatpat123!

**Comment by wilkinsona** [comment]
I'm a member of the Spring Boot team and I've been following this issue since it was [originally raised on Stack Overflow](https://stackoverflow.com/questions/72054870/spring-boot-starter-data-cassandra-reactive-depends-on-cve-2020-13946-native-pro/72056181#72056181). Just wanted to say that, FWIW, I agree with the analysis that this should be fixed in the OWASP plugin (or in the data which it consumes). There's nothing that we can do about this from a Spring perspective.
